# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class kb_functional_enrichment_1(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def run_fe1(self, params, context=None):
        """
        run_fe1: run functional enrichment one
        :param params: instance of type "FEOneInput" (required params:
           genome_ref: Genome object reference workspace_name: the name of
           the workspace it gets saved to) -> structure: parameter
           "genome_ref" of type "obj_ref" (An X/Y/Z style reference),
           parameter "workspace_name" of String
        :returns: instance of type "FEOneResult" (result_directory: folder
           path that holds all files generated by run_deseq2_app report_name:
           report name generated by KBaseReport report_ref: report reference
           generated by KBaseReport) -> structure: parameter
           "result_directory" of String, parameter "report_name" of String,
           parameter "report_ref" of String
        """
        return self._client.call_method(
            'kb_functional_enrichment_1.run_fe1',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('kb_functional_enrichment_1.status',
                                        [], self._service_ver, context)
